name: checkout-credentials

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  push:
    branches: [master]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"

permissions:
  contents: read

jobs:
  audit:
    uses: florianhorner/gh-workflows/.github/workflows/checkout-credentials.yml@687f5d52b91f55d1d9073eaec0221c2a4aa2ebc9 # checkout-credentials v1
