name: checkout-credentials

on:
  pull_request_target:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  push:
    branches: [master]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"

permissions:
  contents: read
  pull-requests: read

jobs:
  audit-pr:
    if: github.event_name == 'pull_request_target'
    uses: florianhorner/gh-workflows/.github/workflows/checkout-credentials.yml@0e567126859f67eebab0bbe6859509afddcbd33d # checkout-credentials v1.1
    with:
      pull_request_number: ${{ github.event.pull_request.number }}

  audit-push:
    if: github.event_name == 'push'
    uses: florianhorner/gh-workflows/.github/workflows/checkout-credentials.yml@0e567126859f67eebab0bbe6859509afddcbd33d # checkout-credentials v1.1
